name: Rest React App
on: push
jobs: 
  test_app:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code!
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test app
        run: npm run test